'use client'
import { useEffect, useState } from 'react'
import useWindowDimensions from '~/hooks/use-window-dimensions'

interface MicroAdProps {
  unitIdDesktop: string
  unitIdMobile: string
  className: string
  condition: string
}

const MicroAd: React.FC<MicroAdProps> = ({
  unitIdMobile,
  unitIdDesktop,
  className,
  condition,
}) => {
  const { width } = useWindowDimensions()
  const [unitId, setUnitId] = useState(unitIdMobile)
  const [isShown, setIsShown] = useState(true)

  useEffect(() => {
    setUnitId(width && width < 1200 ? unitIdMobile : unitIdDesktop)
    switch (condition) {
      case '!isTablet': {
        if (!width) break
        setIsShown(width >= 1200 || width < 768)
        break
      }
      case 'isTablet': {
        if (!width) break
        setIsShown(width < 1200 || width >= 768)
        break
      }
      default: {
        setIsShown(true)
      }
    }
  }, [width])

  useEffect(() => {
    const insertScript = () => {
      const microAdScript = document.createElement('script')
      microAdScript.id = `compass-fit-script-${unitId}`
      microAdScript.type = 'text/javascript'
      microAdScript.charset = 'UTF-8'
      microAdScript.async = true
      microAdScript.src = `${document.location.protocol}//nt.compass-fit.jp/lift_widget.js?adspot_id=${unitId}`
      document.head.appendChild(microAdScript)
    }

    const removeScript = () => {
      const microAdScript = document.querySelector(
        `#compass-fit-script-${unitId}`
      )
      microAdScript?.remove()
      const autoGeneratedScript = document.querySelector(
        `script[src*="${unitId}"]`
      )
      autoGeneratedScript?.remove()
      const microAdStyles = Array.from(document.querySelectorAll('style'))
      const microAdStyle = microAdStyles.find((item) =>
        item.textContent?.includes(`#compass-fit-${unitId}`)
      )
      microAdStyle?.remove()
    }

    insertScript()
    return () => {
      removeScript()
    }
  }, [unitId])

  if (!isShown) return null

  return <div id={`compass-fit-${unitId}`} className={`mic-ad ${className}`} />
}

export default MicroAd
